batvat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('bats/', views.bat_index, name='bat-index'),
    path('bats/<int:bat_id>/', views.bat_detail, name='bat-detail'),
    path('bats/create/', views.BatCreate.as_view(), name='bat-create'),
    path('bats/<int:pk>/update/', views.BatUpdate.as_view(), name='bat-update'),
    path('bats/<int:pk>/delete/', views.BatDelete.as_view(), name='bat-delete'),
    path(
        'bats/<int:bat_id>/add-feeding/', 
        views.add_feeding, 
        name='add-feeding'
    ),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('toys/', views.toy_index, name='toy-index'),
    path('toys/<int:toy_id>/', views.toy_detail, name='toy-detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toy-create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toy-update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toy-delete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

batvat/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User


MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toy-detail', kwargs={'pk': self.id})


class Bat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    image = models.ImageField(upload_to='bats/', blank=True, null=True)

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('bat-detail', kwargs={'bat_id': self.id})

    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

class Feeding(models.Model):
    date = models.DateField('Feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    bat = models.ForeignKey(Bat, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

batvat/forms.py
from django import forms
from .models import Feeding

class FeedingForm(forms.ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

batvat/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Bat, Toy
from .forms import FeedingForm
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



class Home(LoginView):
    template_name = 'home.html'


def about(request):
    return render(request, 'bats/about.html')

@login_required
def bat_index(request):
    bats = Bat.objects.filter(user=request.user)
    return render(request, 'bats/index.html', {'bats': bats})



@login_required
def bat_detail(request, bat_id):
    bat = Bat.objects.get(id=bat_id, user=request.user)
    feeding_form = FeedingForm()
    return render(request, 'bats/detail.html', {
        'bat': bat, 'feeding_form': feeding_form
    })

class BatCreate(LoginRequiredMixin, CreateView):
    model = Bat
    fields = ['name', 'breed', 'description', 'age', 'image']
    template_name = 'bats/bat_form.html'
    success_url = '/bats/'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('bat-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)


class BatUpdate(LoginRequiredMixin, UpdateView):
    model = Bat
    fields = ['name', 'breed', 'description', 'age', 'image']
    template_name = 'bats/bat_form.html'
    success_url = '/bats/'

class BatDelete(LoginRequiredMixin, DeleteView):
    model = Bat
    template_name = 'bats/bat_confirm_delete.html'
    success_url = '/bats/'

@login_required
def add_feeding(request, bat_id):
    form = FeedingForm(request.POST)
    if form.is_valid():

        new_feeding = form.save(commit=False)
        new_feeding.bat_id = bat_id
        new_feeding.save()
    return redirect('bat-detail', bat_id=bat_id)

@login_required
def toy_index(request):
    toys = Toy.objects.filter(user=request.user)
    return render(request, 'toys/index.html', {'toys': toys})

@login_required
def toy_detail(request, toy_id):
    toy = Toy.objects.get(id=toy_id, user=request.user)
    return render(request, 'toys/detail.html', {'toy': toy})

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = ['name', 'color']
    template_name = 'toys/toy_form.html'
    success_url = '/toys/'
    
    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = ['name', 'color']
    template_name = 'toys/toy_form.html'
    success_url = '/toys/'

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    template_name = 'toys/toy_confirm_delete.html'
    success_url = '/toys/'

batvat/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'css/images/baticon.png' %}"/>
    <title>Bat Vat</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&display=swap" rel="stylesheet">
   
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    {% block head %}
    {% endblock %}
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'bat-index' %}">All Bats</a></li>
            <li><a href="{% url 'toy-index' %}">All Toys</a></li>
            <li><a href="{% url 'bat-create' %}">Add a Bat</a></li>
            <li><a href="{% url 'toy-create' %}">Add a Toy</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
          {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

batvat/templates/bats/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h1>About the BatVat</h1>
<center> 
 Welcome to the BatVat, where you can keep track of your bats, their feedings and toys.
 <br><br> 
 <br>Sign up to get started, or login with your existing account. 
<br>Add a bat to your collection, and then add a feeding and a toy to track their activity.
<br>Browse All Bats to see what others are up to.

 <img src="{% static 'css/images/batvatxl.png' %}" alt="BatVat Logo" style="width: 65%; height: 65%;" />


</div>
</center>
{% endblock %}

batvat/templates/bats/bat_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Bat?</h1>
  <img src="{% static 'images/nerd-bat.svg' %}" alt="A bat using a computer" />
</div>

<h2>Are you sure you want to delete {{ bat.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'bat-detail' bat.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

batvat/templates/bats/bat_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bats/bat-form.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">        {% if bat %}
          <h1>Edit {{ bat.name }}</h1>
        {% else %}
          <h1>Add a New Bat</h1>
        {% endif %}
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Name:</label>
            {{ form.name }}
        </div>
        
        <div class="form-group">
            <label for="{{ form.breed.id_for_label }}">Breed:</label>
            {{ form.breed }}
        </div>
        
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Description:</label>
            {{ form.description }}
        </div>
        
        <div class="form-group">
            <label for="{{ form.age.id_for_label }}">Age:</label>
            {{ form.age }}
        </div>
        
        <div class="form-group">
            <label for="{{ form.image.id_for_label }}">Bat Photo:</label>
            {{ form.image }}
        </div>
        
        <button type="submit" class="btn btn-primary">Add Bat</button>
    </form>
    
    <a href="{% url 'bat-index' %}" class="btn btn-secondary">Back to Bat List</a>
</div>
{% endblock %}

batvat/templates/bats/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/bats/bat-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="bat-container">
  <div class="bat-img">
    {% if bat.image %}
      <img src="{{ bat.image.url }}" alt="{{ bat.name }}" />
    {% else %}
      <img src="{% static 'css/images/baticon.png' %}" alt="{{ bat.name }}" />
    {% endif %}
  </div>
  <div class="bat-details">
    <h1>{{ bat.name }}</h1>
    {% if bat.age > 0 %}
      <h2>A {{ bat.age }} year old {{ bat.breed }}</h2>
    {% else %}
      <h2>A {{ bat.breed }} baby bat.</h2>
    {% endif %}
    <p>{{ bat.description }}</p>
  
    <div class="bat-actions">
      <a href="{% url 'bat-update' bat.id %}" class="btn warn">Edit</a>
      <a href="{% url 'bat-delete' bat.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>

<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Feedings</h2>
    </div>

    <h3>Add a Feeding</h3>
    <form
      action="{% url 'add-feeding' bat.id %}"
      method="post"
      class="subsection-content"
      autocomplete="off"
    >
      {% csrf_token %} 
      {{ feeding_form.as_p }}
      <button type="submit" class="btn submit">Add Feeding</button>
    </form>
    

    <h3>Past Feedings</h3>
    {% if bat.feeding_set.all.count %}
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Meal</th>
          </tr>
        </thead>
        <tbody>
          {% for feeding in bat.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="subsection-content">
        <p>⚠️ {{bat.name}} has not been fed!</p>
      </div>
    {% endif %}
    

{% endblock %}

batvat/templates/bats/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/bats/bat-index.css' %}">
{% endblock %}

{% block content %}
<h1>BatVat Index</h1>
<p>Welcome to the bats section!</p>

<section class="card-container">
{% for bat in bats %}
  <div class="card">
<a href="{% url 'bat-detail' bat.id %}">
    <div class="card-content">
      {% if bat.image %}
        <img src="{{ bat.image.url }}" alt="{{ bat.name }}" class="bat-img">
      {% else %}
        <img src="{% static 'css/images/baticon.png' %}" alt="{{ bat.name }}" class="bat-img">
      {% endif %}
      <h2>{{ bat.name }}</h2>
      <p>Breed: {{ bat.breed }}</p>
      <p>Age: {{ bat.age }}</p>
      <p>Description: {{ bat.description }}</p>
    </div>
    </a>
  </div>
{% endfor %}
</section>

{% endblock %}

batvat/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div class="about-container">
Login or sign up to get started with BatVat.
</div>

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}
{% endblock %}

batvat/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/nerd-bat.svg' %}" alt="" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

batvat/templates/toys/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/toys/toy-detail.css' %}">
{% endblock %}

{% block content %}
<h1>{{ toy.name }}</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ toy.name }}</span>
    <p>Color: {{ toy.color }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'toy-update' toy.id %}">Edit</a>
    <a href="{% url 'toy-delete' toy.id %}">Delete</a>
  </div>
</div>

<div class="card-action">
  <a href="{% url 'toy-index' %}" class="btn">Back to All Toys</a>
</div>

{% endblock %}

batvat/templates/toys/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/toys/toy-index.css' %}">
{% endblock %}

{% block content %}
<h1>Toy List</h1>

{% if toys %}
  {% for toy in toys %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toy-detail' toy.id %}">View Details</a>
        <a href="{% url 'toy-update' toy.id %}">Edit</a>
        <a href="{% url 'toy-delete' toy.id %}">Delete</a>
      </div>
    </div>
  {% endfor %}
{% else %}
  <p>No toys available</p>
{% endif %}

<div class="card-action">
  <a href="{% url 'toy-create' %}" class="btn">Add a New Toy</a>
</div>

{% endblock %}

batvat/templates/toys/toy_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Delete Toy</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ toy.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'toy-detail' toy.id %}">Cancel</a>
</form>

{% endblock %}

batvat/templates/toys/toy_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/toys/toy-form.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header">
    {% if toy %}
      <h1>Edit {{ toy.name }}</h1>
    {% else %}
      <h1>Add a New Toy</h1>
    {% endif %}
  </div>

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

  <div class="card-action">
    <a href="{% url 'toy-index' %}" class="btn">Cancel</a>
  </div>
</div>

{% endblock %}